/*
 * ManagerViewSupplierDetailsJPanel.java
 *
 * Created on October 9, 2008, 10:45 PM
 */

package UserInterface.SupplierRole;

import Business.Supplier.Supplier;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Rushabh
 */
public class AdministrativeViewSupplierDetailsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Supplier supplier;
   
    public AdministrativeViewSupplierDetailsJPanel(JPanel upc, Supplier s) {
        initComponents();
        userProcessContainer = upc;
        supplier = s;
        
        nameTextField1.setText(s.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateSuppJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nameTextField1 = new javax.swing.JTextField();
        saveButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 20));

        updateSuppJButton.setText("Update");
        updateSuppJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSuppJButtonActionPerformed(evt);
            }
        });
        add(updateSuppJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, -1));

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));
        add(nameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 230, 30));

        saveButton1.setText("SAVE");
        saveButton1.setEnabled(false);
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        add(saveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateSuppJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSuppJButtonActionPerformed

        nameTextField1.setEditable(true);
        saveButton1.setEnabled(true);
        
    }//GEN-LAST:event_updateSuppJButtonActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        
        supplier.setName(nameTextField1.getText());
        nameTextField1.setEditable(false);
        saveButton1.setEnabled(false);
        
    }//GEN-LAST:event_saveButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton updateSuppJButton;
    // End of variables declaration//GEN-END:variables
    
}
