/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Organization.CustomersOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ketki
 */
public class NewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewCustomerJPanel
     */
    private UserAccount userAccount;
    
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    OrganizationDirectory organizationDirectory;
    
    public NewCustomerJPanel(JPanel userProcessContainer,EcoSystem ecoSystem, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.organizationDirectory = organizationDirectory;
        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        emailid = new javax.swing.JTextField();
        pwd = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Welcome New customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 29, 189, 34));

        jLabel2.setText("First name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 84, -1, -1));

        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 122, -1, -1));

        jLabel4.setText("Email id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 160, -1, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 239, -1, -1));

        jLabel7.setText("City");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 277, -1, -1));

        back.setText("Back");
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 328, 59, -1));

        signup.setText("Sign Up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 328, -1, -1));
        add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 81, 144, -1));
        add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 119, 144, -1));
        add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 157, 144, -1));
        add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 236, 144, -1));
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 274, 144, -1));

        jLabel6.setText("username");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 198, -1, -1));
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 195, 144, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        String firstName = fname.getText();
        String lastName = lname.getText();
        String emailid1 =emailid.getText();
        String password = pwd.getText();
        String city1 = city.getText();
        String username1 = username.getText();
        
       
        
       Customer c = new Customer();
        c.setFirstName(firstName);
        c.setLastName(lastName);
        c.setEmailid(emailid1);
        c.setPwd(password);
        c.setCity(city1);
        c.setUsername(username1); 
        
        
        Organization organization = null;
        organization = new CustomersOrganization();
//        organizationDirectory.createOrganization(Organization.Type.Customer);
        userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(username1,password,null,new CustomerRole(), c);
        ecoSystem.getCustomerDirectory().getCustomerList().add(c);
      
        if(fname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "PlEASE ENTER FIRST NAME");
         }
        else if(lname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER A LAST NAME");
        }
        else if(emailid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER AN EMAIL ID");
            
        }
        else if(pwd.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"PLEASE ENTER A VALID PASSWORD");
        }
        else if(username.getText().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER A VALID USERNAME");
            
        }
        else if(city.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"PLEASE ENTER A VALID CITY");
        }
       
        else if(pwd.getText().length()<3)
            //jTextField1.getText().length()==0 || jTextField2.getText().length()==0)
        {
             JOptionPane.showMessageDialog(null,"PLEASE ENTER ATLEAST A THREE LETTER PASSWPRD");
        }
        
        
    }//GEN-LAST:event_signupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField city;
    private javax.swing.JTextField emailid;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField pwd;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
