/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InvoiceRole;

import Business.WorkQueue.PaymentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ketki
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {
private WorkRequest workRequest;
private JPanel container;
    /**
    /**
     * Creates new form ProcessRequestJPanel
     */
    public ProcessRequestJPanel(WorkRequest Request, JPanel container) {
        initComponents();
        this.container = container;
        workRequest = Request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitjButton = new javax.swing.JButton();
        testResultjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });
        add(submitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 59, -1, -1));
        add(testResultjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 60, 86, -1));

        jLabel1.setText("Amount Paid");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 63, -1, -1));

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        // TODO add your handling code here:
        ((PaymentWorkRequest)workRequest).setAmountPaid(testResultjTextField.getText());

        workRequest.setStatus("Completed");

    }//GEN-LAST:event_submitjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField testResultjTextField;
    // End of variables declaration//GEN-END:variables
}
