/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;
import Business.EcoSystem;
import Business.Invoice.InvoiceDirectory;
import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ketki
 */
public class BrowseJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private MasterOrderCatalog masterOrderCatalog;
    private InvoiceDirectory invoiceDirectory;
    
    /**
     * Creates new form BrowseJPanel
     */
    public BrowseJPanel(JPanel userProcessContainer, MasterOrderCatalog masterOrderCatalog, InvoiceDirectory invoiceDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.masterOrderCatalog = masterOrderCatalog;
        this.invoiceDirectory = invoiceDirectory;
        
        populateOrderTable();
    }

    private void populateOrderTable()
   {
       DefaultTableModel model = (DefaultTableModel)orderjTable.getModel();
       model.setRowCount(0);
     //userProcessContainer.remove(this);
       for(Order o : masterOrderCatalog.getOrderList())
       {
           Object row[] = new Object[1];
           row[0] = o; 
           model.addRow(row);
           
        
       }
   }
    
    
    private void populateOrderItemTable(Order o)
   {
       if(o == null)
       {
           return;
       }
       DefaultTableModel model = (DefaultTableModel)orderItemjTable.getModel();
       model.setRowCount(0);
       for(OrderItem oi :o.getOrderItemList())
       {
           Object row[] = new Object[4];
           row[0] = oi.getProduct();
           row[1] = oi.getQuantity();
           row[2] = oi.getProduct().getActualPrice();
         //  row[3] = oi.getInvoice().getStatus();
           model.addRow(row);
           
           totalPricejTextField.setText(String.valueOf(o.totalPrice()));
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemjTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        viewDetailjButton = new javax.swing.JButton();
        totalPricejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        viewInvoicejButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderItemjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Actual Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderItemjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 180, 403, 98));

        orderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ));
        jScrollPane1.setViewportView(orderjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 11, 403, 102));

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 357, -1, -1));

        viewDetailjButton.setText("View Detail");
        viewDetailjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailjButtonActionPerformed(evt);
            }
        });
        add(viewDetailjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 139, -1, -1));
        add(totalPricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 305, 76, -1));

        jLabel2.setText("Amount Due");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 308, -1, -1));

        viewInvoicejButton.setText("View Invoice");
        viewInvoicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInvoicejButtonActionPerformed(evt);
            }
        });
        add(viewInvoicejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 357, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void viewDetailjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailjButtonActionPerformed

        int selectedRow = orderjTable.getSelectedRow();
        
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Order order = (Order)orderjTable.getValueAt(selectedRow, 0);
     //   order.getInvoice().setStatus("Pending");
        populateOrderItemTable(order);
    }//GEN-LAST:event_viewDetailjButtonActionPerformed

    private void viewInvoicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInvoicejButtonActionPerformed
        // TODO add your handling code here:

        ViewInvoiceJPanel vijp = new ViewInvoiceJPanel(userProcessContainer, masterOrderCatalog, invoiceDirectory);
        userProcessContainer.add("ViewInvoiceJPanel", vijp);

        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewInvoicejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderItemjTable;
    private javax.swing.JTable orderjTable;
    private javax.swing.JTextField totalPricejTextField;
    private javax.swing.JButton viewDetailjButton;
    private javax.swing.JButton viewInvoicejButton;
    // End of variables declaration//GEN-END:variables
}
