/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.EcoSystem;
import Business.Order.MasterOrderCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Invoice.InvoiceDirectory;
import Business.Organization.Organization;
import Business.Supplier.SupplierDirectory;
import UserInterface.EmployeeRole.BrowseProductsJPanel;

/**
 *
 * @author Ketki
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private MasterOrderCatalog masterOrderCatalog;
    private InvoiceDirectory invoiceDirectory;
    private EcoSystem system;
    private SupplierDirectory supplierDirectory;

    public CustomerWorkAreaJPanel() {
    }
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, MasterOrderCatalog masterOrderCatalog, InvoiceDirectory invoiceDirectory, EcoSystem system, SupplierDirectory supplierDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.masterOrderCatalog = masterOrderCatalog;
        this.invoiceDirectory = invoiceDirectory;
        this.system = system;
        this.supplierDirectory=supplierDirectory;
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseOrdersjButton = new javax.swing.JButton();
        browseProductjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        browseOrdersjButton.setText("View Orders");
        browseOrdersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOrdersjButtonActionPerformed(evt);
            }
        });
        add(browseOrdersjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 110, 120, -1));

        browseProductjButton.setText("Browse Product Catalog >>");
        browseProductjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseProductjButtonActionPerformed(evt);
            }
        });
        add(browseProductjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void browseOrdersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOrdersjButtonActionPerformed
        // TODO add your handling code here:
        BrowseJPanel bjp = new BrowseJPanel(userProcessContainer, masterOrderCatalog, invoiceDirectory);
        userProcessContainer.add("CustomerWorkAreaJPanel", bjp);
        
        CardLayout cardLayout =(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_browseOrdersjButtonActionPerformed

    private void browseProductjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseProductjButtonActionPerformed
        BrowseProductsJPanel bpjp = new BrowseProductsJPanel(userProcessContainer, supplierDirectory, masterOrderCatalog, system);
        userProcessContainer.add("BrowseProductsJPanel", bpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_browseProductjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseOrdersjButton;
    private javax.swing.JButton browseProductjButton;
    // End of variables declaration//GEN-END:variables
}
