/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Invoice.Invoice;
import Business.Invoice.InvoiceDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ketki
 */
public class MakePaymentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private InvoiceDirectory invoiceDirectory;
    
    /**
     * Creates new form MakePaymentJPanel
     */
    public MakePaymentJPanel(JPanel userProcessContainer,InvoiceDirectory invoice) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.invoiceDirectory = invoice;
        
        populateCombobox();
    }

    private void populateCombobox()
    {
        paymentjComboBox.removeAllItems();
        
        paymentjComboBox.addItem("Visa");
        paymentjComboBox.addItem("Mastercard");
        paymentjComboBox.addItem("American Express");
        paymentjComboBox.addItem("Paypal");
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paymentjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardNumberjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountPaidjTextField = new javax.swing.JTextField();
        submitjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        expirydatejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        securityCodejTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Payment Details");

        paymentjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Select Payment option");

        jLabel3.setText("Card Number");

        jLabel4.setText("Amount paid");

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Expiry Date");

        jLabel6.setText("Security Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(amountPaidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cardNumberjTextField)
                                    .addComponent(expirydatejTextField)
                                    .addComponent(securityCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(paymentjComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(backjButton)
                        .addGap(69, 69, 69)
                        .addComponent(submitjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(paymentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(amountPaidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(cardNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(expirydatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(securityCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton)
                    .addComponent(submitjButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        Invoice i = invoiceDirectory.addInvoice();
        i.setCardNumber(cardNumberjTextField.getText());
        i.setAmountPaid(amountPaidjTextField.getText());
        i.setExpiryDate(expirydatejTextField.getText());
        i.setSecurityCode(securityCodejTextField.getText());
        
     /*   PaymentWorkRequest paymentWorkRequest = new PaymentWorkRequest();
        paymentWorkRequest.setSender(userAccount);
        paymentWorkRequest.setMessage(amountPaidjTextField.getText());
        paymentWorkRequest.setStatus("Sent");
        
        Organization invoiceOrganization = null;
        for(Organization o : business.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof InvoiceManagementOrganization)
            {
                invoiceOrganization = o;
            }
        }
        
        invoiceOrganization.getWorkQueue().getWorkRequestList().add(paymentWorkRequest);
        userAccount.getWorkQueue().getWorkRequestList().add(paymentWorkRequest);
        populateTable(); */
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountPaidjTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField cardNumberjTextField;
    private javax.swing.JTextField expirydatejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox paymentjComboBox;
    private javax.swing.JTextField securityCodejTextField;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
