/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Customer.Customer;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author Ketki
 */
public class ViewCustomerDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Customer customer;
    /**
     * Creates new form ViewCustomerDetailsJPanel
     */
    public ViewCustomerDetailsJPanel(JPanel upc, Customer c) {
        initComponents();
        
        userProcessContainer = upc;
        customer = c;
        
    //    namejTextField1.setText(c.getCustomerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namejTextField1 = new javax.swing.JTextField();
        saveButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateSuppJButton = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(namejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 89, 143, -1));

        saveButton1.setText("SAVE");
        saveButton1.setEnabled(false);
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        add(saveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 146, 72, 22));

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 92, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("CUSTOMER DETAILS");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 26, -1, -1));

        updateSuppJButton.setText("Update");
        updateSuppJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSuppJButtonActionPerformed(evt);
            }
        });
        add(updateSuppJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 146, 90, -1));

        backjButton2.setText("<<BACK");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 146, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed

   //     customer.setCustomerName(namejTextField1.getText());
   //     namejTextField1.setEditable(false);
    //    saveButton1.setEnabled(false);
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void updateSuppJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSuppJButtonActionPerformed

        namejTextField1.setEditable(true);
        saveButton1.setEnabled(true);
    }//GEN-LAST:event_updateSuppJButtonActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton updateSuppJButton;
    // End of variables declaration//GEN-END:variables
}
