/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EmployeeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.Organization.PackagingManagementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PackagingWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ketki
 */
public class BrowseOrdersJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private MasterOrderCatalog masterOrderCatalog;
    private Enterprise system;
    private UserAccount userAccount;

    
    public BrowseOrdersJPanel(JPanel userProcessContainer, MasterOrderCatalog masterOrderCatalog, UserAccount userAcccount, Enterprise system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.masterOrderCatalog = masterOrderCatalog;
        this.system = system;
        this.userAccount = userAcccount;
        
        populateOrderTable();
    }

    
   private void populateOrderTable()
   {
       DefaultTableModel model = (DefaultTableModel)orderjTable.getModel();
       model.setRowCount(0);
     //  userProcessContainer.remove(this);
       for(Order o : masterOrderCatalog.getOrderList())
       {
           Object row[] = new Object[1];
           row[0] = o; 
           model.addRow(row);
       }
   }
   
   private void populateOrderItemTable(Order o)
   {
       if(o == null)
       {
           return;
       }
       DefaultTableModel model = (DefaultTableModel)orderItemjTable.getModel();
       model.setRowCount(0);
       for(OrderItem oi :o.getOrderItemList())
       {
           Object row[] = new Object[2];
           row[0]= oi.getProduct();
           row[1] = oi.getQuantity();
           model.addRow(row);
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderjTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemjTable = new javax.swing.JTable();
        viewDetailjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        submitjButton = new javax.swing.JButton();
        submitjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ));
        jScrollPane1.setViewportView(orderjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 11, 403, 102));

        orderItemjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(orderItemjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 228, 403, 98));

        viewDetailjButton.setText("View Detail");
        viewDetailjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailjButtonActionPerformed(evt);
            }
        });
        add(viewDetailjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 139, -1, -1));

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 139, -1, -1));

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });
        add(submitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));
        add(submitjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailjButtonActionPerformed
        
        int selectedRow = orderjTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Order order = (Order)orderjTable.getValueAt(selectedRow, 0);
        populateOrderItemTable(order);
    }//GEN-LAST:event_viewDetailjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        // TODO add your handling code here:
        
        PackagingWorkRequest packagingWorkRequest = new PackagingWorkRequest();
        packagingWorkRequest.setSender(userAccount);
        packagingWorkRequest.setMessage(submitjTextField.getText());
        packagingWorkRequest.setStatus("Sent");

        Organization packagingOrganization = null;
        for(Organization o : system.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof PackagingManagementOrganization)
            {
                packagingOrganization = o;
            }
        }
        packagingOrganization.getWorkQueue().getWorkRequestList().add(packagingWorkRequest);
        userAccount.getWorkQueue().getWorkRequestList().add(packagingWorkRequest);
    }//GEN-LAST:event_submitjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderItemjTable;
    private javax.swing.JTable orderjTable;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField submitjTextField;
    private javax.swing.JButton viewDetailjButton;
    // End of variables declaration//GEN-END:variables
}
