/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.EmployeeRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.MasterOrderCatalog;
import Business.Organization.Organization;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;






/**
 *
 * @author Rushabh
 */
public class EmployeeWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    SupplierDirectory supplierDir;
    MasterOrderCatalog masterOrderCatalog;
    Organization organization;
    private EcoSystem system;
    private Enterprise enterprise;
    private UserAccount userAccount;
   

    /** Creates new form ProductManagerWorkAreaJPanel */
    public EmployeeWorkAreaJPanel(JPanel userProcessContainer,SupplierDirectory supplierDir, MasterOrderCatalog masterOrderCatalog, EcoSystem system, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.supplierDir = supplierDir;
        this.userProcessContainer = userProcessContainer;
        this.masterOrderCatalog = masterOrderCatalog;
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
               
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        browseProductjButton = new javax.swing.JButton();
        browseOrderjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("My Work Area (Employee Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        browseProductjButton.setText("Browse Product Catalog >>");
        browseProductjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseProductjButtonActionPerformed(evt);
            }
        });
        add(browseProductjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        browseOrderjButton.setText("Browse Orders");
        browseOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOrderjButtonActionPerformed(evt);
            }
        });
        add(browseOrderjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void browseProductjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseProductjButtonActionPerformed
        BrowseProductsJPanel bpjp = new BrowseProductsJPanel(userProcessContainer, supplierDir, masterOrderCatalog, system);
        userProcessContainer.add("BrowseProductsJPanel", bpjp);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_browseProductjButtonActionPerformed

    private void browseOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOrderjButtonActionPerformed
        // TODO add your handling code here:
        BrowseOrdersJPanel bojp = new BrowseOrdersJPanel(userProcessContainer, masterOrderCatalog, userAccount, enterprise);
        userProcessContainer.add("BrowseProductsJPanel", bojp);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_browseOrderjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseOrderjButton;
    private javax.swing.JButton browseProductjButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
