/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EmployeeRole;
import Business.Enterprise.Enterprise;
import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.CustomersOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PaymentWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ketki
 */
public class InvoiceJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private MasterOrderCatalog masterOrderCatalog;
    private Enterprise system;
    private UserAccount userAccount;

    /**
     * Creates new form InvoiceJPanel
     */
    public InvoiceJPanel(JPanel userProcessContainer, MasterOrderCatalog masterOrderCatalog,UserAccount userAcccount, Enterprise system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.masterOrderCatalog = masterOrderCatalog;
        this.userAccount = userAcccount;
        this.system = system;
        
        populateOrderItemTable();
    }

     private void populateOrderItemTable()
   {
       DefaultTableModel model = (DefaultTableModel)orderItemsjTable.getModel();
       model.setRowCount(0);
       for(Order o : masterOrderCatalog.getOrderList())
       for(OrderItem oi :o.getOrderItemList())
       {
           Object row[] = new Object[3];
           row[0]= oi.getProduct();
           row[1] = oi.getQuantity();
           row[2] = oi.getProduct().getActualPrice();
           
           model.addRow(row);
           
        totalPricejTextField.setText(String.valueOf(o.totalPrice()));
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemsjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        totalPricejTextField = new javax.swing.JTextField();
        requestTestjButton = new javax.swing.JButton();
        messagejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderItemsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Actual Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderItemsjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 580, 97));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("INVOICE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 21, -1, -1));

        jLabel2.setText("Total Price:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 223, -1, -1));
        add(totalPricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 197, 76, -1));

        requestTestjButton.setText("Request Test");
        requestTestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestjButtonActionPerformed(evt);
            }
        });
        add(requestTestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));
        add(messagejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 97, -1));

        jLabel3.setText("Message");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void requestTestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestjButtonActionPerformed
        // TODO add your handling code here:

        PaymentWorkRequest paymentWorkRequest = new PaymentWorkRequest();
        paymentWorkRequest.setSender(userAccount);
        paymentWorkRequest.setMessage(messagejTextField.getText());
        paymentWorkRequest.setStatus("Sent");

        Organization customerOrganization = null;
        for(Organization o : system.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof CustomersOrganization)
            {
                customerOrganization = o;
            }
        }

        customerOrganization.getWorkQueue().getWorkRequestList().add(paymentWorkRequest);
        userAccount.getWorkQueue().getWorkRequestList().add(paymentWorkRequest);
        populateOrderItemTable();

    }//GEN-LAST:event_requestTestjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messagejTextField;
    private javax.swing.JTable orderItemsjTable;
    private javax.swing.JButton requestTestjButton;
    private javax.swing.JTextField totalPricejTextField;
    // End of variables declaration//GEN-END:variables
}
