/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */

package UserInterface.EmployeeRole;

import Business.Product.Product;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class ViewProductDetailJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Product product;
    
  
    /** Creates new form CreateProductJPanel */
    public ViewProductDetailJPanel(JPanel upc, Product p) {
        initComponents();
        userProcessContainer = upc;
        product = p;
        
        productNamejTextField.setText(p.getName());
        productIDjTextField.setText(String.valueOf(p.getProductId()));
        actualpricejTextField.setText(String.valueOf(p.getActualPrice()));
        productTargetPricejTextField.setText(String.valueOf(p.getTargetPrice()));
        availabilityjTextField.setText(String.valueOf(p.getAvailability()));
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        actualpricejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productTargetPricejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        availabilityjTextField = new javax.swing.JTextField();
        productNamejTextField = new javax.swing.JTextField();
        productIDjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Product Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        backButton3.setText("<< BACK");
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });
        add(backButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 88, -1));

        jLabel5.setText("Product ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setText("Product Actual Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        actualpricejTextField.setEditable(false);
        actualpricejTextField.setEnabled(false);
        add(actualpricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, -1));

        jLabel6.setText("Product Target Price:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        productTargetPricejTextField.setEditable(false);
        productTargetPricejTextField.setEnabled(false);
        add(productTargetPricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, -1));

        jLabel7.setText("Availability:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        availabilityjTextField.setEditable(false);
        availabilityjTextField.setEnabled(false);
        add(availabilityjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, -1));

        productNamejTextField.setEditable(false);
        productNamejTextField.setEnabled(false);
        add(productNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, -1));

        productIDjTextField.setEditable(false);
        productIDjTextField.setEnabled(false);
        add(productIDjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton3ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualpricejTextField;
    private javax.swing.JTextField availabilityjTextField;
    private javax.swing.JButton backButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField productIDjTextField;
    private javax.swing.JTextField productNamejTextField;
    private javax.swing.JTextField productTargetPricejTextField;
    // End of variables declaration//GEN-END:variables
    
}
