/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Network.Country;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    
    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        manageCountryjButton = new javax.swing.JButton();
        manageStatejButton = new javax.swing.JButton();
        manageLocationjButton = new javax.swing.JButton();
        submitjButton = new javax.swing.JButton();

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        manageCountryjButton.setText("Manage Country");
        manageCountryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCountryjButtonActionPerformed(evt);
            }
        });

        manageStatejButton.setText("Manage State");
        manageStatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStatejButtonActionPerformed(evt);
            }
        });

        manageLocationjButton.setText("Manage City");
        manageLocationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLocationjButtonActionPerformed(evt);
            }
        });

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(69, 69, 69)
                .addComponent(submitjButton)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manageCountryjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageLocationjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageStatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(manageCountryjButton)
                .addGap(36, 36, 36)
                .addComponent(manageStatejButton)
                .addGap(29, 29, 29)
                .addComponent(manageLocationjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitjButton)
                    .addComponent(backJButton))
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
       
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void manageLocationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLocationjButtonActionPerformed
        // TODO add your handling code here:
        
        ManageLocationJPanel manageLocationJPanel = new ManageLocationJPanel(userProcessContainer, system);
        userProcessContainer.add("manageLocationJPanel", manageLocationJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageLocationjButtonActionPerformed

    private void manageStatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStatejButtonActionPerformed
        // TODO add your handling code here:
        
        ManageStateJPanel manageStateJPanel = new ManageStateJPanel(userProcessContainer, system);
        userProcessContainer.add("manageStateJPanel", manageStateJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStatejButtonActionPerformed

    private void manageCountryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCountryjButtonActionPerformed
        // TODO add your handling code here:
        ManageCountryJPanel manageCountryJPanel = new ManageCountryJPanel(userProcessContainer, system);
        userProcessContainer.add("manageCountryJPanel", manageCountryJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCountryjButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_submitjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton manageCountryjButton;
    private javax.swing.JButton manageLocationjButton;
    private javax.swing.JButton manageStatejButton;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
