/*
 * SystemAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Country;
import Business.Network.Location;
import Business.Network.State;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author  raunak
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Country country;
    State state;
    /** Creates new form SystemAdminWorkAreaJPanel */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        
        populateTree();
    }
    
    
    private void populateTree(){
        
        DefaultTreeModel model = (DefaultTreeModel)jTreeforEcoSystem.getModel();
        
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        
        ArrayList<Country> networkList = system.getCountryList();
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode entNode;
        for(int i = 0; i < networkList.size(); i++){
            Country net = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(net.getCountry());
            root.insert(networkNode, 0);
         
           ArrayList<State> stateList = net.getStateNetworkList();
           State state = stateList.get(i);
           networkNode = new DefaultMutableTreeNode(state.getState());
           root.insert(networkNode, 1);
           
           ArrayList<Location> locationList = state.getLocationNetworkList();
           Location loc = locationList.get(i);
           networkNode = new DefaultMutableTreeNode(loc.getLocation());
           root.insert(networkNode, 2);
           
           
            
            ArrayList<Enterprise> enList = loc.getEnterpriseDirectory().getEnterpriseList();
            for(int j = 0; j < enList.size(); j++){
                Enterprise ent = enList.get(j);
                entNode = new DefaultMutableTreeNode(ent.getName());
                networkNode.insert(entNode, j);
            }
            
        }
        model.reload();
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageEnterpriseAdminJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageNetworkJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeforEcoSystem = new javax.swing.JTree();
        refreshjButton = new javax.swing.JButton();
        nodejLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        manageEnterpriseAdminJButton.setText("Manage Enterprise Admin");
        manageEnterpriseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminJButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 200, -1));

        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 200, -1));

        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });
        add(manageNetworkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 200, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        jTreeforEcoSystem.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeforEcoSystem.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeforEcoSystemValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeforEcoSystem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 440));

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });
        add(refreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));
        add(nodejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 34, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEnterpriseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed

        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed

        populateTree();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void jTreeforEcoSystemValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeforEcoSystemValueChanged
        
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)jTreeforEcoSystem.getLastSelectedPathComponent();
        if(node != null){
            nodejLabel.setText(node.toString());
        }
        
    }//GEN-LAST:event_jTreeforEcoSystemValueChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeforEcoSystem;
    private javax.swing.JButton manageEnterpriseAdminJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JLabel nodejLabel;
    private javax.swing.JButton refreshjButton;
    // End of variables declaration//GEN-END:variables
    
}
